#!/usr/bin/env bash
set -euo pipefail

# Detect the default router
router=$(ip route show default | awk '{print $3; exit}')

# Run the LAN host connectivity check
migrant ssh -- "uv run ~/netcheck.py --no-interactive --lan-ip $router"
